name: Build Cartesi Anvil Devnet

on:
  push:
    branches:
      - 'release/cartesi-devnet/**'

jobs:
  build-espresso-dev-node:
    name: Build Cartesi Anvil Devnet
    runs-on: ubuntu-latest
    env:
      COMPOSE_BAKE: true
      TARGETARCH: amd64
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: devnet_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner.toLower() }}/cartesi-devnet

      - name: Setup espresso date and hash tag
        id: vars
        run: |
          echo "date_tag=$(date +'%Y-%m-%d')-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./devnet
          file: ./devnet/Dockerfile
          push: true
          build-args: |
            TARGETARCH=amd64
          tags: |
            ghcr.io/${{ github.repository_owner.toLower() }}/cartesi-devnet:latest
            ghcr.io/${{ github.repository_owner.toLower() }}/cartesi-devnet:${{ steps.vars.outputs.date_tag }}
          labels: ${{ steps.devnet_meta.outputs.labels }}
